---

- name: update package cache
  package:
    update_cache: true

- name: deinstall scanbd package
  package:
    name: scanbd
    state: absent

# - name: install same helper packages
#   apt:
#     name: "{{ item }}"
#     state: present
#     install_recommends: false
#   loop:
#     - bc
#     - unpaper
#     - poppler-utils
#     - tesseract-ocr
#     - tesseract-ocr-deu
#     - tesseract-ocr-deu-frak
#     - tesseract-ocr-eng
#     - inotify-tools
#     - libconfuse1
#     - imagemagick

# get file or directory stats
- name: detect created scanbd binary
  stat:
    path: "/usr/local/sbin/scanbd"
    get_checksum: false
    get_checksum: false
    get_mime: false
    get_attributes: false
  register: __stat_present_scanbd
  changed_when: not __stat_present_scanbd.stat.exists

# - name: ensure group 'scanner' exists
#   group:
#     name: scanner
#     state: present
#
# - name: ensure user 'saned' exists
#   user:
#     name: saned
#     comment: saned
#     group: scanner
#     shell: /bin/bash
#     home: /var/lib/saned

...
